activities = [
    "diagram model",
    "Code/ML",
    "Build",
    "Test",
    "Create a deployment diagram model",
    "Generating Code",
    "Allocating Resources",
    "Lease resources",
    "Execute Pipeline",
    "Clone Repo",
    "Build Image",
    "Package Pipeline",
    "Upload and Run",
    "Data Process",
    "Model Training",
    "Model Testing",
    "Training requirements and indicators management",
    "Dataset management",
    "Training algorithm management",
    "Model performance management",
    "Data Preprocessing",
    "Model Training",
    "Model evaluation",
    "Model validation",
    "Model Store",
    "Model Serving",
    "Model Monitoring",
    "Model Testing",
    "business problem analysis",
    "design architecture and define technologies",
    "derive ML problem from business goal",
    "understand required data to solve problem",
    "connect to raw data for initial data analysis",
    "define transformation & cleaning rules",
    "define feature engineering rules",
    "connect to raw data",
    "data extraction",
    "data transformation & cleaning",
    "feature engineering",
    "data ingestion job",
    "data analysis",
    "data preparation & validation",
    "model training",
    "model validation",
    "export model",
    "data extraction",
    "data preparation & validation",
    "model training/refinement",
    "model validation",
    "export model",
    "push to model registry",
    "Model and Web Server Building Process",
    "code repository",
    "Build",
    "Test & compile Artifact",
    "Deliver Artifact",
    "artifact repository",
    "Deploy to Staging",
    "Deploy to Production",
    "Logging, Notifying",
    "data schema preparation",
    "modeling",
    "evaluation",
    "deployment",
    "monitoring",
    "prepare data",
    "schedule execution",
    "generate or use cached feature pipelines",
    "execute models on dedicated containers",
    "run functions on model outputs to serve queries",
    "stream data ingestion",
    "data annotation",
    "data storage & versioning",
    "model building & evaluation",
    "model storage & versioning",
    "model deployment & serving",
    "model performance monitoring",
    "learner feedback",
    "learner progress",
    "data analysis/preprocessing",
    "experimentation",
    "model tuning",
    "model serving",
    "model monitoring",
    "model tuning",
    "data preparation",
    "develop",
    "(re-)train",
    "review",
    "deploy",
    "inference",
    "monitor",
    "Dockerfile is defined",
    "domain analysis",
    "system specification",
    "functional & technical architecture description",
    "data preparation",
    "ML model design",
    "ML model training",
    "ML model verification",
    "non-ML software design & implementation",
    "ML/Software integration",
    "virtual field test",
    "Hardware/Software integration",
    "field test",
    "system operation in the field",
    "Data Engineering",
    "Model development",
    "model deployment",
    "Model-accuracy monitoring",
    "Training data creation + retraining",
    "plan (ML and Non-ML)",
    "code (ML and Non-ML)",
    "validation",
    "build",
    "test",
    "release",
    "deploy",
    "operate",
    "monitor",
    "data ingestion",
    "model (re-)training",
    "model evaluation",
    "model packaging",
    "model registering",
    "CI/CD pipeline triggering",
    "testing (data sanity test, unit test, integration test)",
    "build and release artifacts",
    "project requirement gathering",
    "science quality (data cleaning)",
    "data quality",
    "stewardship quality",
    "use & service quality",
    "ML data acquisition",
    "dataset preprocessing",
    "data versioning",
    "problem/pipeline structure search",
    "algorithm & hyperparameter selection",
    "model version",
    "model validation",
    "solution deployment",
    "model integration into application",
    "model & application monitoring",
    "CI/CD validation",
    "ingestion",
    "preparation",
    "feature selection",
    "data analysis",
    "build model",
    "model training",
    "model evaluation",
    "deployment",
    "performance monitoring",
    "service engineering",
    "data ingestion",
    "data preprocessing",
    "model training",
    "model evaluation",
    "model validation",
    "experiment tracking",
    "data preprocessing",
    "model training",
    "registration",
    "versioning",
    "build",
    "test",
    "push",
    "continuous deployment",
    "model programming",
    "model training",
    "model assessment",
    "model releasing",
    "model deployment",
    "plan",
    "create",
    "adapt and optimize",
    "verify",
    "package",
    "release",
    "configure",
    "monitor",
    "data collection",
    "data analysis",
    "Digital signal processing pipeline",
    "ML design and training",
    "estimation and evaluation",
    "optimization and compression",
    "conversion and compilation",
    "IoT device management",
    "production monitoring",
    "train & publish model and dataset",
    "initialize streaming consumers with model version",
    "make predictions based on streaming events",
    "save predictions",
    "match predictions to ground truth",
    "train & publish new model version based on labeled predictions",
    "notify streaming consumers about new model version",
    "streaming consumers request new model version",
    "understanding and framing the problem",
    "data preparation and exploratory data analysis",
    "feature selection",
    "model design & selection",
    "deploy model to production",
    "monitoring and retraining model (if required)",
    "model training, deployment, and orchestration",
    "storing model metadata",
    "storing trained model in registry",
    "model serving",
    "model monitoring",
    "retraining trigger",
    "model comparison",
    "collecting model information from retraining and comparison",
    "data provisioning with governance",
    "data preparation",
    "model development",
    "model validation & governance",
    "model deployment & insight consumption",
    "model monitoring",
    "model ML problem",
    "search for similar problem in problem DB",
    "get similar dataset or build dataset",
    "generate model development strategy",
    "train model",
    "evaluate model",
    "register model and metadata",
    "deploy model",
    "monitor model",
    "data validation",
    "data preprocessing",
    "model training",
    "model validation",
    "deploy for serving",
    "monitor",
    "business requirements definition",
    "requirements analysis",
    "architectural design",
    "data ingestion",
    "data preparation",
    "data analysis",
    "experimentation",
    "model analysis",
    "CI: build, test and package pipeline",
    "CD: pipeline deployment",
    "data engineering",
    "ML model engineering",
    "CD: model serving",
    "model monitoring",
    "Data preprocessing",
    "Model Inference",
    "Decision Processing",
    "data collection",
    "data analysis",
    "data preparation",
    "model building",
    "model training",
    "model evaluation",
    "model selection",
    "model packaging",
    "CI/CD testing",
    "model deployment",
    "monitoring",
    "data preparation",
    "model building",
    "model packaging",
    "CI/CD testing",
    "monitoring",
    "Development",
    "source code",
    "pipeline continuous integration",
    "packages",
    "pipeline continuous delivery",
    "automated pipeline",
    "continuous training",
    "trained model",
    "monitoring",
    "continuous delivery",
    "monitoring continuous delivery",
    "prediction service",
    "new data",
    "continuous training",
    "monitoring",
    "collect log",
    "preprocess data",
    "train/retrain model",
    "test model",
    "deploy model",
    "Project Conceptualization",
    "Model Development",
    "Model Validation",
    "Deployment and Operation",
    "Monitoring and Maintenance",
    "Security",
    "Data Acquisition",
    "Preprocessing",
    "Feature Engineering",
    "Experiment",
    "Optimize",
    "Evaluate",
    "Package",
    "Validate",
    "Deploy",
    "Monitor",
    "Data Acquisition",
    "Data Processing",
    "Model Building and Training",
    "Evaluation and Interpretation",
    "Model Packaging and Deployment",
    "Data Collection",
    "Initial Data Analysis",
    "Data Transformation and Cleaning",
    "Feature Engineering",
    "data preparation",
    "Model Training",
    "Model Evaluation",
    "model validation",
    "Data Extraction",
    "Model Training",
    "Model Evaluation",
    "model validation",
    "Deployment",
    "Monitoring",
    "Data Acquisition",
    "Data Processing",
    "Data Preparation",
    "Model Training & Testing",
    "Packaging",
    "Deployment & Serving",
    "Monitoring",
    "Data Analysis",
    "Data and Model pipeline (experimentation)",
    "Model Analysis",
    "CI: Build, Test, and Package Pipeline",
    "CD: Pipeline Deployment",
    "Data and Model pipeline (automated)",
    "CD: Model Serving",
    "Prediction Service",
    "Performance monitoring",
    "Continuous Training Trigger",
    "Data Engineering",
    "Model Training",
    "CI/CD for ML",
    "Model Deployment",
    "Monitoring and Maintenance",
    "Defining the Issue",
    "Identifying the Data Sources",
    "Collecting the Data",
    "Preparing the Data",
    "Labeling the Data",
    "Validating the Data",
    "Data Cleaning",
    "Data Normalization",
    "Feature Engineering",
    "Data Augmentation",
    "Label Encoding",
    "Hyperparameter",
    "Cross-Validation",
    "Ensemble Learning",
    "Transfer Learning",
    "Model Containerization",
    "Configuring Infrastructure",
    "Deploying the Model to a Testing Environment",
    "Running Tests",
    "Deploying the Model to Production",
    "Model Monitoring",
    "Data Collection",
    "data preparation",
    "Model Training",
    "Transforming to Model Lite",
    "Evaluation",
    "Tuning",
    "Deployment",
    "Monitoring",
    "Data Source",
    "Data Collector",
    "Data Preprocessor",
    "Dataset Catalogue",
    "Dataset Repository",
    "Raw Data Store",
    "Feature Store",
    "Code Repository",
    "Model Repository",
    "Artifact Repository",
    "Data Transformation",
    "Feature Engineering",
    "Feature Store",
    "Hyperparameter Tuning",
    "Model Training",
    "Model evaluation",
    "Model Store",
    "Model Deployment",
    "Model Monitoring",
    "Business process analysis",
    "Data Collection",
    "Feature Selection",
    "Data Validation",
    "Data Analysis",
    "Data Preprocessing",
    "Model training",
    "Model evaluation",
    "Model Registration",
    "CI/CD",
    "Model Monitoring"
]